In [1]:
pip install fastapi uvicorn

     |████████████████████████████████| 51 kB 175 kB/s 
     |████████████████████████████████| 54 kB 1.5 MB/s 
     |████████████████████████████████| 10.1 MB 12.3 MB/s 
     |████████████████████████████████| 61 kB 210 kB/s 
     |████████████████████████████████| 78 kB 5.7 MB/s 
     |████████████████████████████████| 54 kB 2.4 MB/s 


In [2]:
pip install tensorflow==2.0.0

     |████████████████████████████████| 86.3 MB 16 kB/s 
     |████████████████████████████████| 3.8 MB 33.0 MB/s 
     |████████████████████████████████| 449 kB 52.3 MB/s 
     |████████████████████████████████| 50 kB 5.7 MB/s 
  Created wheel for gast: filename=gast-0.2.2-py3-none-any.whl size=7554 sha256=d4e143aad712cc108e709104d2a783707181b4aae6728f2e00a9f770d001984a
  Stored in directory: /root/.cache/pip/wheels/21/7f/02/420f32a803f7d0967b48dd823da3f558c5166991bfd204eef3
Successfully built gast
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.7.0
    Uninstalling tensorflow-estimator-2.7.0:
      Successfully uninstalled tensorflow-estimator-2.7.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.7.0
    Uninstalling tensorboard-2.7.0:
      Successfully uninstalled tensorboard-2.7.0
  Attempting uninstall: gast
    Found existing installation: gast 0.4.0
    Uninstalling gast-0.4.0:
      Success

In [3]:
pip install colabcode

     |████████████████████████████████| 745 kB 3.9 MB/s 
     |████████████████████████████████| 8.3 MB 29.0 MB/s 
     |████████████████████████████████| 45 kB 2.2 MB/s 
     |████████████████████████████████| 428 kB 40.5 MB/s 
     |████████████████████████████████| 58 kB 3.9 MB/s 
     |████████████████████████████████| 394 kB 33.4 MB/s 
     |████████████████████████████████| 125 kB 53.1 MB/s 
     |████████████████████████████████| 52 kB 992 kB/s 
     |████████████████████████████████| 124 kB 49.6 MB/s 
     |████████████████████████████████| 124 kB 41.4 MB/s 
     |████████████████████████████████| 122 kB 34.6 MB/s 
     |████████████████████████████████| 122 kB 32.8 MB/s 
     |████████████████████████████████| 122 kB 41.1 MB/s 
     |████████████████████████████████| 122 kB 43.0 MB/s 
     |████████████████████████████████| 112 kB 39.1 MB/s 
     |████████████████████████████████| 69 kB 4.3 MB/s 
  Created wheel for pyngrok: filename=pyngrok-5.1.0-py3-none-any.whl size=19006 s

In [4]:
pip install heroku

     |████████████████████████████████| 233 kB 6.2 MB/s 
  Created wheel for heroku: filename=heroku-0.1.4-py3-none-any.whl size=12365 sha256=17faae97ee39d56e489b94091c59737049637257c9077bf8191f6bf0207c02ff
  Stored in directory: /root/.cache/pip/wheels/e1/03/d7/ec6e018e04b7b2e9afe6c2ca1047cc5ab1bb266c8586aa1a29
  Created wheel for python-dateutil: filename=python_dateutil-1.5-py3-none-any.whl size=203005 sha256=2d126fe2b6d8d31e5d7f68075c56403342ae613b3a8d19940cff1034c50fb4f4
  Stored in directory: /root/.cache/pip/wheels/33/3c/58/1384eaa15bd3be2988a813b9241241b386b16bf9305f72d300
Successfully built heroku python-dateutil
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.8.2
    Uninstalling python-dateutil-2.8.2:
      Successfully uninstalled python-dateutil-2.8.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pandas 

In [5]:
pip install "uvicorn[standard]"

     |████████████████████████████████| 219 kB 4.2 MB/s 
     |████████████████████████████████| 596 kB 42.6 MB/s 
     |████████████████████████████████| 79 kB 4.1 MB/s 
     |████████████████████████████████| 3.8 MB 34.5 MB/s 
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bokeh 2.3.3 requires python-dateutil>=2.1, but you have python-dateutil 1.5 which is incompatible.


In [6]:
!pip install fastapi nest-asyncio pyngrok uvicorn

In [7]:
pip install python-multipart

  Created wheel for python-multipart: filename=python_multipart-0.0.5-py3-none-any.whl size=31678 sha256=ae6b634a34d9febbaebcad239bfe0ea16cc3e80b37ecfff017273c886ff6ccf8
  Stored in directory: /root/.cache/pip/wheels/2c/41/7c/bfd1c180534ffdcc0972f78c5758f89881602175d48a8bcd2c
Successfully built python-multipart


In [32]:
import pandas as pd
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM, SpatialDropout1D
from sklearn.model_selection import train_test_split
import re
import pickle

In [118]:
data = pd.read_csv('/content/Sentiment.csv')

In [117]:
data = data[['text','sentiment']]
data.head()

text sentiment
0   nancyleegrahn how did everyone feel about the...   Neutral
1   scottwalker didnt catch the full gopdebate la...  Positive
2   tjmshow no mention of tamir rice and the gopd...   Neutral
3   robgeorge that carly fiorina is trending  hou...  Positive
4   danscavino gopdebate w realdonaldtrump delive...  Positive

In [119]:
def preProcess_data(text):
  text = text.lower()
  new_text = re.sub('[^a-zA-z0-9\s]','', text)
  new_text = re.sub('rt', '', new_text)
  return new_text

data['text'] = data['text'].apply(preProcess_data)  


In [120]:
max_features = 2000

tokenizer = Tokenizer(num_words = max_features, split = ' ') # break text into tokens
tokenizer.fit_on_texts(data['text'].values) # text to numerical value
X = tokenizer.texts_to_sequences(data['text'].values)
X = pad_sequences(X, 28) # make sure all sequences have the same length

Y = pd.get_dummies(data['sentiment']).values # set the labesl to values
print(Y)

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.20) # split the data

embed_dim = 128
lstm_out = 196

model = Sequential()
model.add(Embedding(max_features, embed_dim, input_length = X.shape[1])) # represent words as vectors
model.add(SpatialDropout1D(0.4))
model.add(LSTM(lstm_out, dropout = 0.3, recurrent_dropout = 0.2, return_sequences=True))
model.add(LSTM(128, recurrent_dropout= 0.2))
model.add(Dense(3, activation = 'softmax'))

model.compile(loss = 'categorical_crossentropy', optimizer='adam',metrics = ['accuracy'])


batch_size = 512
model = model.fit(X_train, Y_train, epochs = 10, batch_size = batch_size, validation_data= (X_test, Y_test))
pickle.dump(model.history, open("model_nlp.pkl", "wb"))



[[0 1 0]
 [0 0 1]
 [0 1 0]
 ...
 [0 0 1]
 [1 0 0]
 [0 0 1]]
Train on 11096 samples, validate on 2775 samples
Epoch 1/10


Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x7f74bcbab0e0>
Traceback (most recent call last):
  File "/usr/lib/python3.7/weakref.py", line 358, in remove
    def remove(k, selfref=ref(self)):
KeyboardInterrupt


 1536/11096 [===>..........................] - ETA: 53s - loss: 1.0889 - accuracy: 0.4883 

KeyboardInterrupt: ignored

In [104]:
import numpy as np
from fastapi import FastAPI, Form
import pandas as pd
from starlette.responses import HTMLResponse
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import tensorflow as tf
import re

In [51]:
!pip install flask

In [52]:
!pip install flask-ngrok

FASTAPI and RESTAPI

In [53]:
from flask import *
from flask_ngrok import run_with_ngrok

In [109]:
from fastapi import FastAPI
import nest_asyncio
from pyngrok import ngrok
import uvicorn

# Create the form and endpoint for API
app = FastAPI(title = "NLP ML web app using Google Colab", description= "with FastAPI and Colab" )
# post method is used to post

@app.get("/", response_class=HTMLResponse)
async def take_inp():
          return '''
                <form method="post">
                <input maxlength="28" name="text" type="text" value="Text Emotion to be tested" />
                <input type="submit" />'''

# ngrok_tunnel = ngrok.connect(8000)
# print('Public URL:', ngrok_tunnel.public_url)
# nest_asyncio.apply()
# uvicorn.run(app, port=8000)




In [110]:
cc.run_app(app = app)

Public URL: NgrokTunnel: "https://e512-104-155-205-193.ngrok.io" -> "http://localhost:8000"


INFO:     Started server process [61]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)


INFO:     64.229.234.61:0 - "GET / HTTP/1.1" 200 OK
INFO:     64.229.234.61:0 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     206.248.151.137:0 - "GET / HTTP/1.1" 200 OK


INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [61]


In [121]:
def pre_Process_data(text):
  text = text.lower()
  new_text = re.sub('[^a-zA-z0-9\s]', '', text)
  new_text = re.sub('rt', '', new_text)
  return new_text

def my_pipeline(text):
  text_new = preProcess_data(text)
  X = tokenizer.texts_to_sequences(pd.Series(text_new).values)
  X = pad_sequences(X, maxlen = 28)
  return X


Now for user interaction

In [128]:
# when opening the app, load the ml model
@app.on_event("startup")
async def load_model():
  global model
  model = pickle.load(open('/content/model_nlp.pkl', "rb"))

@app.post("/api", tags = ["prediction"])
async def predict(text:str = Form(...)):
  clean_text = my_pipeline(text) # clean and preprocess the text through pipeline
  # loaded_model = tf.keras.models.load_model('/content/sentiment.h5')
  predictions = model.predict(clean_text)
  sentiment = int(np.argmax(predictions)) # calculate the index of the sentiment
  probability = max(predictions.tolist()[0]) # calculate the probability
  if sentiment==0:
    t_sentiment = 'negative' # set for appropriate sentiment
  elif sentiment==1:
    t_sentiment = 'neutral'
  elif sentiment==2:
    t_sentiment=='positive'
  return {
      "ACTUAL SENTENCE": text,
      "PREDICTED SENTIMENT": t_sentiment,
      "Probability": probability
  }



In [129]:
ngrok_tunnel = ngrok.connect(8000)
print('Public URL:', ngrok_tunnel.public_url)
nest_asyncio.apply()
uvicorn.run(app, port=8000)

Public URL: http://258b-104-155-205-193.ngrok.io


INFO:     Started server process [61]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)


INFO:     64.229.234.61:0 - "GET / HTTP/1.1" 200 OK
INFO:     64.229.234.61:0 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     96.21.0.7:0 - "GET / HTTP/1.1" 200 OK
INFO:     64.229.234.61:0 - "GET /docs HTTP/1.1" 200 OK
INFO:     64.229.234.61:0 - "GET /docs HTTP/1.1" 200 OK
INFO:     198.235.201.68:0 - "GET /docs HTTP/1.1" 200 OK
INFO:     198.235.201.68:0 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error


ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/dist-packag

INFO:     64.229.234.61:0 - "GET /docs HTTP/1.1" 200 OK
INFO:     64.229.234.61:0 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error


ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/dist-packag

In [18]:
from colabcode import ColabCode

In [130]:
cc = ColabCode(port = 12000, code = False)

pyngrok

In [31]:
! pip install pyngrok

In [131]:
cc.run_app(app=app)

Public URL: NgrokTunnel: "https://11fa-104-155-205-193.ngrok.io" -> "http://localhost:12000"


INFO:     Started server process [61]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:12000 (Press CTRL+C to quit)


INFO:     64.229.234.61:0 - "GET / HTTP/1.1" 200 OK
INFO:     64.229.234.61:0 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     66.130.90.75:0 - "GET / HTTP/1.1" 200 OK
INFO:     64.229.234.61:0 - "GET /docs HTTP/1.1" 200 OK
INFO:     206.80.249.107:0 - "GET /docs HTTP/1.1" 200 OK
INFO:     206.80.249.107:0 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error


ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/dist-packag

INFO:     64.229.234.61:0 - "GET /docs HTTP/1.1" 200 OK
INFO:     64.229.234.61:0 - "GET /openapi.json HTTP/1.1" 500 Internal Server Error


ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/dist-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/dist-packag